In [20]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel(r"C:\Users\Ratan Kumar Jha\Desktop\attendence_analysis\new_att_2x24_P_A_Data_new.xlsx")

In [10]:
df.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\attendence_analysis\att_2024_2023_M_D_ATT_P_DATA.csv",index=False)

In [31]:
att_2024_2023_M_D_ATT_P_DATA=pd.read_csv(r"C:\Users\Ratan Kumar Jha\Desktop\attendence_analysis\att_2024_2023_M_D_ATT_P_DATA_NEW_CHECK.csv")

In [32]:
att_2024_2023_M_D_ATT_P_DATA.head()

,date,DAY,Eric LEHOUELLEUR,Babita Thakur,Mohit Jain,Narendra Prasad Mohanty,Argha Basu,Mukul Miglani,Aashish Sharma,Anand Shimar,...,Satyam Kumar,Praveen Kumar,Saurabh Sharma,Prabhat Ranjan Azad,Rohit Dayal,Ratan Kumar Jha,Sunny Walia,Manish Samkaria,Yoshita Pandey,Abhishek Mishra
0,01-07-2023,Saturday,holiday,holiday,holiday,holiday,NaN,holiday,holiday,holiday,...,holiday,holiday,holiday,holiday,holiday,NaN,NaN,NaN,NaN,NaN
1,02-07-2023,Sunday,holiday,holiday,holiday,holiday,NaN,holiday,holiday,holiday,...,holiday,holiday,holiday,holiday,holiday,NaN,NaN,NaN,NaN,NaN
2,03-07-2023,Monday,present,present,WFH,Not Present with approval/info,NaN,WFH,present,present,...,present,present,present,present,present,NaN,NaN,NaN,NaN,NaN
3,04-07-2023,Tuesday,PATNA,present,WFH,Not Present with approval/info,NaN,WFH,present,present,...,present,present,present,present,present,NaN,NaN,NaN,NaN,NaN
4,05-07-2023,Wednesday,present,present,present,WFH,NaN,present,present,present,...,present,present,present,present,present,NaN,NaN,NaN,NaN,NaN

In [33]:
att_2024_2023_M_D_ATT_P_DATA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      184 non-null    object
 1   DAY                       184 non-null    object
 2   Eric LEHOUELLEUR          184 non-null    object
 3   Babita Thakur             184 non-null    object
 4   Mohit Jain                184 non-null    object
 5   Narendra Prasad Mohanty   184 non-null    object
 6   Argha Basu                21 non-null     object
 7   Mukul Miglani             184 non-null    object
 8   Aashish Sharma            184 non-null    object
 9   Anand Shimar              184 non-null    object
 10  Rajiv Aggarwal            149 non-null    object
 11  Vikas Kumar Sharma        184 non-null    object
 12  Digvijay                  184 non-null    object
 13  Kuldeep KUMAR             184 non-null    object
 14  Ikmeet Singh BAINS        184 non-null    object
 15  Riya Priya                184 non-null    object
 16  Sanjay Tiwari             38 non-null     object
 17  Manoj Kumar               184 non-null    object
 18  Ramniwas Chauhan          149 non-null    object
 19  Sanjit Gupta              184 non-null    object
 20  Manish Tiwari / Reliver   184 non-null    object
 21  Amnesh                    184 non-null    object
 22  Karn Kumar                184 non-null    object
 23  Amit Gupta                184 non-null    object
 24  Sudhanshu Ranjan          184 non-null    object
 25  Satyam Kumar              184 non-null    object
 26  Praveen Kumar             184 non-null    object
 27  Saurabh Sharma            184 non-null    object
 28  Prabhat Ranjan Azad       184 non-null    object
 29  Rohit Dayal               184 non-null    object
 30  Ratan Kumar Jha           161 non-null    object
 31  Sunny Walia               77 non-null     object
 32  Manish Samkaria           70 non-null     object
 33  Yoshita Pandey            61 non-null     object
 34  Abhishek Mishra           42 non-null     object
dtypes: object(35)
memory usage: 50.4+ KB

In [34]:
#att_2024_2023_M_D_ATT_P_DATA['date'] = pd.to_datetime(att_2024_2023_M_D_ATT_P_DATA['date'])
att_2024_2023_M_D_ATT_P_DATA['date']  = att_2024_2023_M_D_ATT_P_DATA['date'] .astype('str')

In [35]:
from datetime import datetime
import pandas as pd

# Assuming 'date' column is in the format "%d-%m-%Y"
att_2024_2023_M_D_ATT_P_DATA['date'] = pd.to_datetime(att_2024_2023_M_D_ATT_P_DATA['date'], format="%d-%m-%Y")

In [38]:
att_2024_2023_M_D_ATT_P_DATA.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\attendence_analysis\att_2024_2023_M_D_ATT_P_DATA_NEW_CHECK.csv",index=False)

In [16]:

att_2024_2023_M_D_ATT_P_DATA_NEW_CHECK=att_2024_2023_M_D_ATT_P_DATA.replace('OFFICE NOT JOINED',np.nan)

In [17]:
att_2024_2023_M_D_ATT_P_DATA_NEW_CHECK.head()

,date,DAY,Eric LEHOUELLEUR,Babita Thakur,Mohit Jain,Narendra Prasad Mohanty,Argha Basu,Mukul Miglani,Aashish Sharma,Anand Shimar,...,Satyam Kumar,Praveen Kumar,Saurabh Sharma,Prabhat Ranjan Azad,Rohit Dayal,Ratan Kumar Jha,Sunny Walia,Manish Samkaria,Yoshita Pandey,Abhishek Mishra
0,2023-07-01,Saturday,holiday,holiday,holiday,holiday,NaN,holiday,holiday,holiday,...,holiday,holiday,holiday,holiday,holiday,NaN,NaN,NaN,NaN,NaN
1,2023-07-02,Sunday,holiday,holiday,holiday,holiday,NaN,holiday,holiday,holiday,...,holiday,holiday,holiday,holiday,holiday,NaN,NaN,NaN,NaN,NaN
2,2023-07-03,Monday,present,present,WFH or LEAVE,Not Present with approval/info,NaN,WFH or LEAVE,present,present,...,present,present,present,present,present,NaN,NaN,NaN,NaN,NaN
3,2023-07-04,Tuesday,PATNA,present,WFH or LEAVE,Not Present with approval/info,NaN,WFH or LEAVE,present,present,...,present,present,present,present,present,NaN,NaN,NaN,NaN,NaN
4,2023-07-05,Wednesday,present,present,present,WFH or LEAVE,NaN,present,present,present,...,present,present,present,present,present,NaN,NaN,NaN,NaN,NaN

In [19]:
att_2024_2023_M_D_ATT_P_DATA_NEW_CHECK.to_csv(r"C:\Users\Ratan Kumar Jha\Desktop\attendence_analysis\att_2024_2023_M_D_ATT_P_DATA_NEW_CHECK.csv",index=False)